# Generated by Django 4.2.2 on 2023-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[(1, '1️⃣'), (2, '2️⃣'), (3, '3️⃣'), (4, '4️⃣'), (5, '5️⃣'), (6, '6️⃣'), (7, '7️⃣'), (8, '8️⃣'), (9, '9️⃣'), (10, '🔟')], max_length=5),
        ),
    ]
